import type { SpeciesProfile } from "./types";

/**
 * Curated reference catalogue, seeded into the `species_profiles` table on
 * first run and referenced by every Pact through a foreign key.
 *
 * PROVENANCE AND HONESTY NOTE
 * The light, temperature and watering ranges below are approximate,
 * widely published horticultural guidelines for each species compiled for
 * this project. They are not measurements of a specific cultivar, and
 * individuals vary a great deal. They are good enough to rank placements
 * and to flag risk; they are not a substitute for local extension advice.
 *
 * The taxonomy columns (family, GBIF usage key, nomenclatural status) are
 * real values fetched from the GBIF Backbone Taxonomy
 * (https://api.gbif.org/v1/species/match) and can be refreshed at runtime
 * through GET /api/species?q=<scientific name>.
 */
export const CATALOGUE: SpeciesProfile[] = [
  {
    slug: "golden-pothos",
    commonName: "Golden pothos",
    scientificName: "Epipremnum aureum",
    family: "Araceae",
    minLightHours: 2,
    maxLightHours: 6,
    minTempC: 13,
    maxTempC: 30,
    waterDays: 8,
    waterToleranceDays: 4,
    difficulty: "easy",
    toxic: true,
    note: "Takes any light except true dark. The most forgiving plant in this catalogue and the usual gift that lives for years.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 2868323,
    gbifFamily: "Araceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "snake-plant",
    commonName: "Snake plant",
    scientificName: "Dracaena trifasciata",
    family: "Asparagaceae",
    minLightHours: 1,
    maxLightHours: 5,
    minTempC: 13,
    maxTempC: 32,
    waterDays: 18,
    waterToleranceDays: 7,
    difficulty: "easy",
    toxic: true,
    note: "Succeeds on neglect. Its failure mode is kindness: too much water, not too little.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 11041822,
    gbifFamily: "Asparagaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "zz-plant",
    commonName: "ZZ plant",
    scientificName: "Zamioculcas zamiifolia",
    family: "Araceae",
    minLightHours: 1,
    maxLightHours: 4,
    minTempC: 15,
    maxTempC: 30,
    waterDays: 21,
    waterToleranceDays: 8,
    difficulty: "easy",
    toxic: true,
    note: "Stores water in its rhizome, so a forgotten fortnight is not a crisis. Frost and cold draughts are.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 2869014,
    gbifFamily: "Araceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "spider-plant",
    commonName: "Spider plant",
    scientificName: "Chlorophytum comosum",
    family: "Asparagaceae",
    minLightHours: 2,
    maxLightHours: 5,
    minTempC: 13,
    maxTempC: 29,
    waterDays: 8,
    waterToleranceDays: 4,
    difficulty: "easy",
    toxic: true,
    note: "Fast, generous and dramatic about its thirst. Brown tips almost always mean tap-water salts or dry air.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 2774846,
    gbifFamily: "Asparagaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "monstera",
    commonName: "Monstera deliciosa",
    scientificName: "Monstera deliciosa",
    family: "Araceae",
    minLightHours: 3,
    maxLightHours: 8,
    minTempC: 16,
    maxTempC: 30,
    waterDays: 9,
    waterToleranceDays: 4,
    difficulty: "moderate",
    toxic: true,
    note: "Grows fast enough that people forget it exists, then collapses from an unnoticed cold window in February.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 2868241,
    gbifFamily: "Araceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "fiddle-leaf-fig",
    commonName: "Fiddle-leaf fig",
    scientificName: "Ficus lyrata",
    family: "Moraceae",
    minLightHours: 5,
    maxLightHours: 8,
    minTempC: 16,
    maxTempC: 27,
    waterDays: 10,
    waterToleranceDays: 3,
    difficulty: "fussy",
    toxic: true,
    note: "The classic gifted plant that dies in a dim hallway. Light demand and a narrow temperature band, with no margin.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 5361899,
    gbifFamily: "Moraceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "calathea-orbifolia",
    commonName: "Calathea orbifolia",
    scientificName: "Goeppertia orbifolia",
    family: "Marantaceae",
    minLightHours: 2,
    maxLightHours: 4,
    minTempC: 18,
    maxTempC: 28,
    waterDays: 5,
    waterToleranceDays: 2,
    difficulty: "fussy",
    toxic: true,
    note: "Wants warmth, soft light, even moisture and humidity. Any one of those missing shows up within a fortnight as curled leaves.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 7476815,
    gbifFamily: "Marantaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "peace-lily",
    commonName: "Peace lily",
    scientificName: "Spathiphyllum wallisii",
    family: "Araceae",
    minLightHours: 2,
    maxLightHours: 5,
    minTempC: 18,
    maxTempC: 29,
    waterDays: 6,
    waterToleranceDays: 3,
    difficulty: "moderate",
    toxic: true,
    note: "Dramatic wilting is reversible, so most people water too much after the first scare and kill it that way.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 2869680,
    gbifFamily: "Araceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "rubber-plant",
    commonName: "Rubber plant",
    scientificName: "Ficus elastica",
    family: "Moraceae",
    minLightHours: 4,
    maxLightHours: 7,
    minTempC: 16,
    maxTempC: 28,
    waterDays: 10,
    waterToleranceDays: 4,
    difficulty: "moderate",
    toxic: true,
    note: "Holds up in a bright hallway and dislikes being moved once it has chosen a spot.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 7835333,
    gbifFamily: "Moraceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "aloe-vera",
    commonName: "Aloe vera",
    scientificName: "Aloe vera",
    family: "Asphodelaceae",
    minLightHours: 5,
    maxLightHours: 10,
    minTempC: 13,
    maxTempC: 32,
    waterDays: 25,
    waterToleranceDays: 12,
    difficulty: "easy",
    toxic: true,
    note: "Rot is the only real danger. A bright, cool, dry corner suits it; a warm damp shelf does not.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 2777724,
    gbifFamily: "Asphodelaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "haworthia",
    commonName: "Zebra haworthia",
    scientificName: "Haworthiopsis attenuata",
    family: "Asphodelaceae",
    minLightHours: 4,
    maxLightHours: 9,
    minTempC: 12,
    maxTempC: 30,
    waterDays: 22,
    waterToleranceDays: 10,
    difficulty: "easy",
    toxic: false,
    note: "Cold tolerant and small. The best choice for a north-facing windowsill in a cold city.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 9388529,
    gbifFamily: "Asphodelaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "string-of-pearls",
    commonName: "String of pearls",
    scientificName: "Curio rowleyanus",
    family: "Asteraceae",
    minLightHours: 3,
    maxLightHours: 7,
    minTempC: 15,
    maxTempC: 27,
    waterDays: 24,
    waterToleranceDays: 9,
    difficulty: "fussy",
    toxic: true,
    note: "Water on the pearls and they rot. Needs the brightest indirect light in the flat and a commitment to let it dry out.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 3149649,
    gbifFamily: "Asteraceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "bird-of-paradise",
    commonName: "White bird of paradise",
    scientificName: "Strelitzia nicolai",
    family: "Strelitziaceae",
    minLightHours: 5,
    maxLightHours: 8,
    minTempC: 16,
    maxTempC: 30,
    waterDays: 9,
    waterToleranceDays: 4,
    difficulty: "moderate",
    toxic: true,
    note: "A floor plant that needs real headroom. Split leaf edges are normal, not a symptom.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 2763112,
    gbifFamily: "Strelitziaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "dracaena-marginata",
    commonName: "Red-edged dracaena",
    scientificName: "Dracaena marginata",
    family: "Asparagaceae",
    minLightHours: 2,
    maxLightHours: 5,
    minTempC: 15,
    maxTempC: 29,
    waterDays: 12,
    waterToleranceDays: 5,
    difficulty: "easy",
    toxic: true,
    note: "Tolerates a north window and an empty fortnight. Genuinely hard to kill by accident.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 10818704,
    gbifFamily: "Asparagaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "pilea",
    commonName: "Chinese money plant",
    scientificName: "Pilea peperomioides",
    family: "Urticaceae",
    minLightHours: 2,
    maxLightHours: 5,
    minTempC: 15,
    maxTempC: 28,
    waterDays: 8,
    waterToleranceDays: 4,
    difficulty: "moderate",
    toxic: false,
    note: "Rotates toward the light, which is how you can tell it wants a better window before the leaves do.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 5669632,
    gbifFamily: "Urticaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "wax-plant",
    commonName: "Wax plant",
    scientificName: "Hoya carnosa",
    family: "Apocynaceae",
    minLightHours: 3,
    maxLightHours: 7,
    minTempC: 15,
    maxTempC: 29,
    waterDays: 12,
    waterToleranceDays: 5,
    difficulty: "moderate",
    toxic: false,
    note: "Slow starter, long-lived reward. Wants bright light and a pot that drains fast.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 8658195,
    gbifFamily: "Apocynaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "echeveria",
    commonName: "Mexican snowball",
    scientificName: "Echeveria elegans",
    family: "Crassulaceae",
    minLightHours: 6,
    maxLightHours: 10,
    minTempC: 12,
    maxTempC: 29,
    waterDays: 20,
    waterToleranceDays: 9,
    difficulty: "easy",
    toxic: false,
    note: "Needs the brightest sill in the flat. Stretching means the light was never enough; a dim window cannot be fixed with water.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 8315197,
    gbifFamily: "Crassulaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "african-violet",
    commonName: "African violet",
    scientificName: "Streptocarpus ionanthus",
    family: "Gesneriaceae",
    minLightHours: 3,
    maxLightHours: 6,
    minTempC: 16,
    maxTempC: 24,
    waterDays: 6,
    waterToleranceDays: 3,
    difficulty: "fussy",
    toxic: false,
    note: "Cold tap water on the leaves causes permanent damage, which is the single most common way these die.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 6710927,
    gbifFamily: "Gesneriaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "parlour-palm",
    commonName: "Parlour palm",
    scientificName: "Chamaedorea elegans",
    family: "Arecaceae",
    minLightHours: 2,
    maxLightHours: 5,
    minTempC: 16,
    maxTempC: 29,
    waterDays: 9,
    waterToleranceDays: 4,
    difficulty: "moderate",
    toxic: true,
    note: "Shade tolerant but not shade proof, and unhappy below 16 °C. A good pick for a north window in a warm flat.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 2734661,
    gbifFamily: "Arecaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "croton",
    commonName: "Croton",
    scientificName: "Codiaeum variegatum",
    family: "Euphorbiaceae",
    minLightHours: 4,
    maxLightHours: 8,
    minTempC: 18,
    maxTempC: 30,
    waterDays: 8,
    waterToleranceDays: 3,
    difficulty: "fussy",
    toxic: true,
    note: "Colour comes from light. Drop leaves usually mean a cold draught, a dry move or too little sun.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 3071476,
    gbifFamily: "Euphorbiaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "boston-fern",
    commonName: "Boston fern",
    scientificName: "Nephrolepis exaltata",
    family: "Nephrolepidaceae",
    minLightHours: 2,
    maxLightHours: 4,
    minTempC: 16,
    maxTempC: 26,
    waterDays: 4,
    waterToleranceDays: 2,
    difficulty: "fussy",
    toxic: false,
    note: "Needs humidity more than anything else. A bathroom with a window is close to ideal; a dry hallway is not.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 2650927,
    gbifFamily: "Nephrolepidaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "jade-plant",
    commonName: "Jade plant",
    scientificName: "Crassula ovata",
    family: "Crassulaceae",
    minLightHours: 4,
    maxLightHours: 8,
    minTempC: 12,
    maxTempC: 29,
    waterDays: 18,
    waterToleranceDays: 8,
    difficulty: "easy",
    toxic: true,
    note: "Survives a cold room and long gaps between drinks. Red leaf edges are a sign of good light, not stress.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 5362063,
    gbifFamily: "Crassulaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "english-ivy",
    commonName: "English ivy",
    scientificName: "Hedera helix",
    family: "Araliaceae",
    minLightHours: 3,
    maxLightHours: 6,
    minTempC: 12,
    maxTempC: 26,
    waterDays: 8,
    waterToleranceDays: 4,
    difficulty: "moderate",
    toxic: true,
    note: "Cold hardy and climbs. Toxic to pets and children if chewed, so placement is the whole decision.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 8351737,
    gbifFamily: "Araliaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "sweet-basil",
    commonName: "Sweet basil",
    scientificName: "Ocimum basilicum",
    family: "Lamiaceae",
    minLightHours: 5,
    maxLightHours: 8,
    minTempC: 18,
    maxTempC: 30,
    waterDays: 3,
    waterToleranceDays: 2,
    difficulty: "moderate",
    toxic: false,
    note: "An edible gift. Dies fast: a cold snap, three dry days or a forgotten weekend and it is finished.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 2927096,
    gbifFamily: "Lamiaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "garden-mint",
    commonName: "Garden mint",
    scientificName: "Mentha spicata",
    family: "Lamiaceae",
    minLightHours: 4,
    maxLightHours: 7,
    minTempC: 15,
    maxTempC: 28,
    waterDays: 3,
    waterToleranceDays: 2,
    difficulty: "easy",
    toxic: true,
    note: "Wants water constantly and does not mind roots in water. Toxic to cats and dogs if eaten in quantity.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 2927175,
    gbifFamily: "Lamiaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "english-lavender",
    commonName: "English lavender",
    scientificName: "Lavandula angustifolia",
    family: "Lamiaceae",
    minLightHours: 7,
    maxLightHours: 10,
    minTempC: 10,
    maxTempC: 28,
    waterDays: 14,
    waterToleranceDays: 7,
    difficulty: "moderate",
    toxic: true,
    note: "Built for a sunny balcony. Indoors it usually gets about half the light it needs and sulks slowly.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 2927305,
    gbifFamily: "Lamiaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "flamingo-flower",
    commonName: "Flamingo flower",
    scientificName: "Anthurium andraeanum",
    family: "Araceae",
    minLightHours: 3,
    maxLightHours: 6,
    minTempC: 18,
    maxTempC: 28,
    waterDays: 7,
    waterToleranceDays: 3,
    difficulty: "moderate",
    toxic: true,
    note: "Blooms in indirect light but will not rest in a cold room. Keep it above 18 °C all winter.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 2872695,
    gbifFamily: "Araceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "rosary-vine",
    commonName: "Rosary vine",
    scientificName: "Ceropegia woodii",
    family: "Apocynaceae",
    minLightHours: 3,
    maxLightHours: 6,
    minTempC: 16,
    maxTempC: 27,
    waterDays: 14,
    waterToleranceDays: 6,
    difficulty: "moderate",
    toxic: false,
    note: "Deliberately plump, so overwatering is the risk. A hanging position away from radiators suits it.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 3572767,
    gbifFamily: "Apocynaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
  {
    slug: "baby-rubber-plant",
    commonName: "Baby rubber plant",
    scientificName: "Peperomia obtusifolia",
    family: "Piperaceae",
    minLightHours: 2,
    maxLightHours: 5,
    minTempC: 18,
    maxTempC: 29,
    waterDays: 10,
    waterToleranceDays: 5,
    difficulty: "easy",
    toxic: false,
    note: "Thick leaves mean real drought tolerance. Hates wet feet in winter more than anything.",
    careSource: "Approximate published ranges",
    gbifUsageKey: 3086423,
    gbifFamily: "Piperaceae",
    gbifStatus: "ACCEPTED",
    taxonomyFetchedAt: null,
  },
];

export const CATALOGUE_BY_SLUG: Record<string, SpeciesProfile> = Object.fromEntries(
  CATALOGUE.map((s) => [s.slug, s]),
);

export function findProfile(slug: string): SpeciesProfile | null {
  return CATALOGUE_BY_SLUG[slug] ?? null;
}

/** Loose text search over the bundled catalogue, used as the offline fallback. */
export function searchCatalogue(query: string): SpeciesProfile[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return CATALOGUE.filter(
    (s) =>
      s.commonName.toLowerCase().includes(q) ||
      s.scientificName.toLowerCase().includes(q) ||
      s.family.toLowerCase().includes(q),
  ).slice(0, 8);
}